import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const root = path.resolve(import.meta.dirname, "..");

test("settings page and bloub renderer remain connected", async () => {
  const app = await readFile(path.join(root, "renderer/src/App.tsx"), "utf8");
  const ball = await readFile(path.join(root, "renderer/src/BloubBall.tsx"), "utf8");
  const settings = await readFile(path.join(root, "renderer/src/ball-settings.ts"), "utf8");

  assert.match(app, /viewMode === "settings"/);
  assert.match(app, /文件路径/);
  assert.match(app, /分类类别/);
  assert.match(app, /画布临时路径/);
  assert.match(ball, /new BotEngine/);
  assert.match(ball, /<mask/);
  assert.match(ball, /window\.addEventListener\("pointermove"/);
  assert.match(ball, /onCursorPosition/);
  assert.match(ball, /bloub-hovered/);
  assert.match(ball, /onPointerEnter/);
  assert.match(app, /setPointerCapture/);
  assert.match(app, /onLostPointerCapture/);
  assert.match(app, /dragStartedRef\.current\) finish\(false\)/);
  assert.match(app, /activePointerRef\.current === event\.pointerId && !dragStartedRef\.current/);
  assert.match(app, /visibilitychange/);
  assert.match(app, /copyImageFiles/);
  assert.match(app, /正在复制图片文件/);
  assert.match(app, /setBusy\(true\)/);
  assert.match(app, /loadError/);
  assert.match(ball, /pointerToLookTarget/);
  assert.match(ball, /setLook\(settings\.followGaze \? [\s\S]*: null/);
  assert.match(ball, /engine\.setLook/);
  assert.match(ball, /REST_STATES/);
  assert.match(ball, /SPARK_STATES/);
  assert.match(settings, /quick-image-board\.ball-settings/);
  await access(path.join(root, "renderer/src/third-party/bloub/LICENSE"));
});

test("canvas authorization iteration keeps image intent and keyboard guards explicit", async () => {
  const app = await readFile(path.join(root, "renderer/src/App.tsx"), "utf8");
  const css = await readFile(path.join(root, "renderer/src/styles.css"), "utf8");
  const ball = await readFile(path.join(root, "renderer/src/BloubBall.tsx"), "utf8");

  assert.match(app, /const \[hoveredId, setHoveredId\]/);
  assert.match(app, /previewId[^\n]*selectedIds[^\n]*hoveredId/);
  assert.match(app, /!panelVisible \|\| busy/);
  assert.match(app, /contenteditable=true/);
  assert.doesNotMatch(app, /onDoubleClick/);
  assert.match(app, /onContextMenu/);
  assert.match(app, /pointerId/);
  assert.match(app, /onLostPointerCapture/);
  assert.match(app, /aria-modal/);
  assert.match(app, /tabIndex=\{0\}/);
  assert.match(app, /selection-rect/);
  assert.match(app, /zoomAroundPoint/);
  assert.match(app, /clampPreviewOffset/);
  assert.match(app, /renameImage/);
  assert.match(app, /deleteClassifiedImages/);
  assert.match(app, /requestAnimationFrame/);
  assert.match(app, /onLostPointerCapture/);
  assert.match(app, /dragDepthRef/);
  assert.match(app, /onDragEnter/);
  assert.match(app, /dropActive/);
  assert.match(app, /library-card/);
  assert.doesNotMatch(app, /library-card[^\n]*onDoubleClick/);
  assert.match(app, /showRemove=\{false\}/);
  assert.match(app, /setSelectedIds\(\[\]\)/);
  assert.match(app, /const selectImage = .*toggleSelection/);
  assert.match(app, /onSelect\(null, image\.id, true\)/);
  const reclassifyHandler = app.match(/<button onClick=\{\(event\) => \{ event\.stopPropagation\(\); ([^}]*) \}\}>重新分类<\/button>/);
  assert.ok(reclassifyHandler, "Library reclassify action should have a dedicated click handler");
  assert.match(reclassifyHandler[1], /onQuickActions\(event, image\.id\)/);
  assert.doesNotMatch(reclassifyHandler[1], /onSelect/);
  assert.match(app, /if \(event\.shiftKey\) onSelect\(event, image\.id, true\); else onPreview\(image\.id\)/);
  assert.match(app, /selectedIds: string\[\]/);
  assert.match(app, /aria-selected=\{selected\}/);
  assert.match(app, /dialogOpen/);
  assert.match(app, /if \(dialogOpen\) return/);
  assert.match(app, /previouslyFocusedRef/);
  assert.match(app, /const focusable/);
  assert.match(app, /Windows 系统回收站/);
  assert.match(app, /不会自动恢复 PicBoard 索引/);
  assert.doesNotMatch(app, /将永久删除 .*已分类图片/);
  const deleteTarget = app.slice(app.indexOf("const deleteTargetIds"), app.indexOf("const handleKeyDown", app.indexOf("const deleteTargetIds")));
  assert.match(deleteTarget, /key === "Delete" && hoveredId && currentCanvasIds\.has\(hoveredId\)/);
  assert.ok(deleteTarget.indexOf("if (previewId") < deleteTarget.indexOf('key === "Delete"'));
  assert.ok(deleteTarget.indexOf('key === "Delete"') < deleteTarget.indexOf("return selectedIds.filter"));
  const copyTarget = app.slice(app.indexOf("const copyTargetIds"), app.indexOf("const deleteTargetIds"));
  assert.doesNotMatch(copyTarget, /hoveredId/);
  assert.match(app, /setSelectionAnchor\(panelAnchorFor\(origin\)\)/);
  assert.match(app, /closest<HTMLElement>\("\.quick-actions, \.preview-card"\)/);
  assert.match(app, /container\.clientWidth - card\.offsetWidth - 12/);
  assert.match(app, /container\.clientHeight - card\.offsetHeight - 12/);
  assert.match(css, /\.quick-actions\.anchored/);
  assert.match(css, /\.library-card\.selected/);
  assert.match(css, /max-height: min\(420px, calc\(100% - 40px\)\)/);
  assert.match(css, /preview-image-wrap\.zoomed/);
  assert.match(css, /bloub-drop-success/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(ball, /dragOpen/);
  assert.match(ball, /bloub-drag-open/);
});
